# Generated by Django 4.1.6 on 2023-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[('FIRST_CLASS', 0), ('SECOND_CLASS', 1), ('THIRD_CLASS', 2)], default=0),
            preserve_default=False,
        ),
    ]
