# Generated by Django 4.1.6 on 2023-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[('FIRST_CLASS', 0), ('SECOND_CLASS', 1), ('THIRD_CLASS', 2)], null=True),
        ),
    ]
