# Generated by Django 4.1.6 on 2023-02-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='creator',
            new_name='owner',
        ),
    ]
