# Generated by Django 4.1.6 on 2023-02-10 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_rename_creator_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='accessible_users',
            field=models.ManyToManyField(related_name='user_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
