# Generated by Django 4.1.6 on 2023-02-11 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_store_is_public_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='accessible_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
