# Generated by Django 4.1.6 on 2023-02-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_store_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wait_time',
        ),
    ]
