# Generated by Django 4.1.6 on 2023-03-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_store_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='accessible_users',
        ),
    ]
